### ISSUE TITLE
Debug error processing new PANC upload

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/GENIE-Sponsored-Projects#59]
```
sh-4.2$ geniesp PANC 1.1-consortium --staging
Welcome, Haley Hunter-Zinck!

INFO:synapseclient_default:Welcome, Haley Hunter-Zinck!

 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   1.6kB/1.6kB (3.5MB/s) SYNAPSE_TABLE_QUERY_88906934.csv Done...
    TREATMENT
Traceback (most recent call last):
  File "/home/ssm-user/.local/bin/geniesp", line 8, in <module>
    sys.exit(main())
  File "/home/ssm-user/.local/lib/python3.7/site-packages/geniesp/__main__.py", line 43, in main
    syn, "../cbioportal", release=args.release, staging=args.staging
  File "/home/ssm-user/.local/lib/python3.7/site-packages/geniesp/bpc_redcap_export_mapping.py", line 932, in run
    timeline_infodf, "TIMELINE-TREATMENT"
  File "/home/ssm-user/.local/lib/python3.7/site-packages/geniesp/bpc_redcap_export_mapping.py", line 606, in make_timeline_treatmentdf
    if "(" in agent:
TypeError: argument of type 'float' is not iterable
```

**Comment by thomasyu888** [comment]
@hhunterzinck this means that agent is probably a blank value.

**Comment by hhunterzinck** [comment]
@thomasyu888 yep, `nan`.  I'm just trying to figure out if this is something new from the derived variable code changes that needs to be brought back to the stats team

**Comment by thomasyu888** [comment]
Maybe a new validation rule? Agent shouldn't be null?

**Comment by hhunterzinck** [comment]
Investigating in the files, the drug_name (AGENT) is null but still has annotated start and stop times.  I think that's what's causing the issue.  Going to have to circle back with the stats team and sites.  This may have to be a data correction.
